enum ERRORS {
  SERVER_ERROR = "SERVER_ERROR",
  NO_FILE_TO_UPLOAD = "NO_FILE_TO_UPLOAD",
  NO_FILES_TO_END = "NO_FILES_TO_END",
  INVALID_DATA = "INVALID_DATA",
  INVALID_FILE = "INVALID_FILE",
  NOT_FOUND = "RESOURCE_NOT_FOUND",
  NO_FILES_ENDED = "NO_FILES_ENDED",
  NO_FILE_STATS_RETRIEVED = "NO_FILE_STATS_RETRIEVED",
}


export { ERRORS };