GET https://h9nn1667-3000.brs.devtunnels.ms/files/stats/DE-0963-01656381-9%20(N) HTTP/1.1

###
GET http://localhost:3000/files/stats/DE-0963-01656381-9%20(N) HTTP/1.1

###
POST https://h9nn1667-3000.brs.devtunnels.ms/files HTTP/1.1

###
POST http://localhost:3000/files/end HTTP/1.1
Content-Type: application/json

[
    {
        "Número": "DE-0010-00485568-0 (N)",
        "Carátula": "SOLIC. LOTE",
        "Ult. actuación": "2009",
        "Finalizado en SIEM": "SI"
    },
    {
        "Número": "DE-0512-00503161-2 (N)",
        "Carátula": "SOLIC. DATOS CATASTRALES Y DOMINIALES",
        "Ult. actuación": "2008",
        "Finalizado en SIEM": ""
    },
    {
        "Número": "DE-0425-00525605-2 (NI)",
        "Carátula": "SUBS. HABITAT Y VIV",
        "Ult. actuación": "2008",
        "Finalizado en SIEM": ""
    },
    {
        "Número": "DE-0512-00500029-4 (N)",
        "Carátula": "SOL. INF. SSEC. DE RESIDUOS MZ 9571",
        "Ult. actuación": "2008",
        "Finalizado en SIEM": ""
    },
    {
        "Número": "DE-0509-00518726-5 (NI)",
        "Carátula": "DIRECCIÓN EJECUTIVA DE PROGRAMA DE VIV. Y PAT COMUNITARIO",
        "Ult. actuación": "2008",
        "Finalizado en SIEM": ""
    },
    {
        "Número": "DE-0509-00504725-3 (NI)",
        "Carátula": "DIRECCIÓN DE PERSONAL",
        "Ult. actuación": "2008",
        "Finalizado en SIEM": ""
    },
    {
        "Número": "DE-0425-00525612-8 (NI)",
        "Carátula": "Subs. Hábitat y Viv",
        "Ult. actuación": "2008",
        "Finalizado en SIEM": ""
    },
    {
        "Número": "DE-0425-00571780-6 (NI)",
        "Carátula": "DATOS CATASTRALES Y DOMINIALES",
        "Ult. actuación": "2009",
        "Finalizado en SIEM": ""
    }
]
