const {
  SIEM_BASE_URL = "",
  LOGIN_PATH = "",
  FILE_STATS_PATH = "",
  SIEM_USER = "",
  SIEM_PASSWORD = "",
  PORT = 3000,
} = process.env;

const FILE_NUMBER_COLUMN_VALID_NAME = "Número";
const FILE_NUMBER_COLUMN_VALIDATION_REGEX =
  /^\w{2}-\d{4}-\d{6,10}-\d+ \(\w{1,2}\)$/;

enum UPLOADS_FOLDER {
  FOLDER = "uploads",
  FILES_CSV = "files.csv",
}

export {
  UPLOADS_FOLDER,
  SIEM_BASE_URL,
  LOGIN_PATH,
  FILE_STATS_PATH,
  SIEM_USER,
  SIEM_PASSWORD,
  PORT,
  FILE_NUMBER_COLUMN_VALID_NAME,
  FILE_NUMBER_COLUMN_VALIDATION_REGEX,
};
