const FILE_NUMBER_COLUMN_VALID_NAME = "Número";

const VALIDATION_REGEX = {
  FILE_NUMBER_COLUMN: /^\w{2}-\d{4}-\d{7,9}-\d+ \(\w{1,2}\)$/,
  FILE_NUMBER_COLUMN_NO_LETTERS: /^\w{2}-\d{4}-\d{7,9}-\d+$/,
};

enum UPLOADS_FOLDER {
  FOLDER = "uploads",
  FILES_CSV = "files.csv",
}

enum MESSAGES {
  FILES_STATS_RETRIEVED = "FILES_STATS_RETRIEVED",
  FILES_ENDED = "FILES_ENDED",
  FILE_UPLOADED = "FILE_UPLOADED",
  SUCCESS = "SUCCESS",
  USER_SESSION_ACTIVE = "USER_SESSION_ACTIVE",
  USER_LOGGED_OUT = "USER_LOGGED_OUT",
  USER_LOGGED_IN = "USER_LOGGED_IN",
  USER_REGISTERED = "USER_REGISTERED",
}

export {
  UPLOADS_FOLDER,
  FILE_NUMBER_COLUMN_VALID_NAME,
  VALIDATION_REGEX,
  MESSAGES,
};
