enum UPLOADS_FOLDER {
  FOLDER = "uploads",
  FILES_CSV = "files.csv",
}

enum MESSAGES {
  FILES_STATS_RETRIEVED = "FILES_STATS_RETRIEVED",
  FILES_ENDED = "FILES_ENDED",
  FILE_UPLOADED = "FILE_UPLOADED",
  SUCCESS = "SUCCESS",
  USER_SESSION_ACTIVE = "USER_SESSION_ACTIVE",
  USER_LOGGED_OUT = "USER_LOGGED_OUT",
  USER_LOGGED_IN = "USER_LOGGED_IN",
  USER_REGISTERED = "USER_REGISTERED",
}

export { UPLOADS_FOLDER, MESSAGES };
